name: Automated Empty Commit

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes for testing

permissions:
  contents: write # Grant permission to write to the repository

jobs:
  make-empty-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@example.com"

    - name: Make Empty Commit
      run: |
        git commit --allow-empty -m "Automated empty commit"
        git push origin HEAD:master
